# Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

name: Build Semgrep Wheel Artifact

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-semgrep-wheel:
    name: Build Semgrep wheel
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Check out Semgrep v1.113.0 repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        repository: semgrep/semgrep.git
        ref: 4729a05d24bf9cee8face447e8a6d418037d61d8
        fetch-depth: 1
        submodules: recursive

    - name: Build wheel through docker
      run: |
        docker build --target semgrep-wheel -t semgrep .
        docker create --name temp semgrep
        mkdir -p wheels/
        docker cp temp:/semgrep/cli/dist/. wheels/
        docker container rm temp

    - name: Log in to GitHub Container Registry
      run: docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push semgrep wheel image
      run: |
        WHEEL_PATH=$(find wheels -type f -name 'semgrep-*manylinux*.whl')
        echo "FROM scratch
        COPY ${WHEEL_PATH} /semgrep_wheel.whl" >> Dockerfile.semgrep
        docker build -t ghcr.io/art1f1c3r/macaron-semgrep-wheel:latest -f Dockerfile.semgrep .
        docker push ghcr.io/art1f1c3r/macaron-semgrep-wheel:latest
